import { useEffect, useState } from "react";
import type { FleetModel, ModelFleetResponse, OpencodeExportResponse } from "../../api/types";
import { fetchModelFleet, fetchOpencodeExport } from "../../api/client";
import { PiMonoCopyButton } from "./PiMonoCopyButton";

const STATUS_COLOR = {
  live: "var(--color-success, #4dbf91)",
  down: "var(--color-danger, #e5594d)",
};

function fmtTokens(n: number): string {
  if (n >= 1e9) return `${(n / 1e9).toFixed(2)}B`;
  if (n >= 1e6) return `${(n / 1e6).toFixed(2)}M`;
  if (n >= 1e3) return `${(n / 1e3).toFixed(1)}K`;
  return `${n}`;
}

function fmtCount(n: number): string {
  return Number.isFinite(n) ? `${n}` : "—";
}

function fmtAgo(ts: number): string {
  const diff = Date.now() - ts;
  if (diff < 60_000) return "just now";
  if (diff < 3_600_000) return `${Math.round(diff / 60_000)}m ago`;
  if (diff < 86_400_000) return `${Math.round(diff / 3_600_000)}h ago`;
  return `${Math.round(diff / 86_400_000)}d ago`;
}

/**
 * Status tag for a fleet row: the currently-served model is `live`, every
 * other (inactive) model is `down`. Deliberately coarse — only one model is
 * /served at a time, so the rest are simply not live.
 */
function StatusBadge({ isLive }: { isLive: boolean }) {
  const key = isLive ? "live" : "down";
  const c = STATUS_COLOR[key];
  return (
    <span
      className="shrink-0 inline-flex items-center gap-1.5 rounded-full px-2 py-0.5 text-[10px] font-semibold"
      style={{
        background: `color-mix(in srgb, ${c} 16%, transparent)`,
        color: c,
        border: `1px solid ${c}`,
      }}
      title={isLive ? "Currently loaded / served on the fleet" : "Not the currently served model"}
    >
      <span className="inline-block h-1.5 w-1.5 rounded-full" style={{ background: c }} />
      {key}
    </span>
  );
}

/**
 * ModelFleetPanel — per-model health + usage for the multi-model fleet.
 *
 * Reads the declarative model registry (config/model-registry.json, generated by
 * the control-plane fleet-sync.py), merges live per node:port /health probes and
 * the coalesced per-user × model token usage from /api/models/fleet.
 *
 * Mirrors the auth-proxy green=healthy / yellow=degraded convention: green when
 * enough replicas are up, yellow when some are down but min_healthy is met, red
 * when the model is effectively down. Feature-flagged so it can be toggled off
 * without touching the existing overview (see README-fleet.md).
 */
export function ModelFleetPanel({ enabled = true }: { enabled?: boolean }) {
  const [data, setData] = useState<ModelFleetResponse | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [showExport, setShowExport] = useState(false);

  useEffect(() => {
    if (!enabled) return;
    let cancelled = false;
    let timer: ReturnType<typeof setTimeout> | null = null;

    const load = async () => {
      try {
        const res = await fetchModelFleet();
        if (!cancelled) {
          setData(res);
          setError(null);
        }
      } catch (err) {
        if (!cancelled) setError(err instanceof Error ? err.message : String(err));
      }
    };

    load();
    timer = setInterval(load, 15_000);
    return () => {
      cancelled = true;
      if (timer) clearInterval(timer);
    };
  }, [enabled]);

  if (!enabled) return null;

  return (
    <div className="panel" style={{ padding: "var(--density-card-pad)" }}>
      <div className="flex flex-wrap items-center justify-between gap-2" style={{ marginBottom: 12 }}>
        <div className="flex items-center gap-2">
          <span className="text-sm font-semibold text-text-strong">Model Fleet</span>
          {data && data.models.length > 0 && (
            <span className="rounded-full bg-surface-hover px-2 py-0.5 text-[10px] font-semibold text-muted">
              {data.models.length} model{data.models.length !== 1 ? "s" : ""}
            </span>
          )}
          {data?.registryLoaded && (
            <button
              type="button"
              onClick={() => setShowExport((v) => !v)}
              className="rounded border border-border px-2 py-0.5 text-[10px] font-semibold text-muted hover:bg-surface-hover hover:text-text-strong transition-colors"
              title="Generate a ready-to-paste opencode.json provider block from the live registry"
            >
              {showExport ? "hide opencode export" : "opencode export"}
            </button>
          )}
        </div>
        <div className="flex items-center gap-2">
          <span className="text-[10px] text-muted">
            {data?.registryLoaded ? "registry-driven" : "registry absent"} · {
              data && data.ts ? new Date(data.ts).toLocaleTimeString() : "—"
            }
          </span>
          {data?.registryLoaded && <PiMonoCopyButton />}
        </div>
      </div>

      {error && (
        <div className="mb-3 rounded-md border border-danger/30 bg-danger/10 px-3 py-2 text-xs text-danger">
          Failed to load model fleet: {error}
        </div>
      )}

      {showExport && <OpencodeExportSection />}

      {!data && !error && (
        <div className="py-6 text-center text-xs text-muted">Loading model fleet…</div>
      )}

      {data && !data.registryLoaded && (
        <div className="mb-3 rounded border border-dashed border-border px-3 py-3 text-center text-xs text-muted">
          No model registry deployed. Run the control-plane sync to generate config/model-registry.json
          (see cliproxyapi/README-fleet.md). Live models served outside the registry will still appear in
          the per-Spark cards.
        </div>
      )}

      {data && data.models.length === 0 && data.registryLoaded && (
        <div className="py-4 text-center text-xs text-muted">Registry loaded but no models declared.</div>
      )}

      {data && data.models.length > 0 && (
        <div className="flex flex-col gap-2">
          {data.models.map((m) => <ModelRow key={m.id} model={m} isLive={isLiveModel(m, data.currentServedId)} />)}
        </div>
      )}
    </div>
  );
}

function isLiveModel(model: FleetModel, currentServedId: string | null): boolean {
  if (!currentServedId) return false;
  if (model.id === currentServedId) return true;
  return !!model.aliases && model.aliases.includes(currentServedId);
}

/**
 * Copy-paste opencode.json provider block generated server-side from the LIVE
 * model-registry.json (regenerated on every fetch — no sparkDash restart, no
 * stale build artifact). The API key is always the {env:CPA_API_KEY}
 * placeholder; this artifact never carries credentials and never writes to
 * remote machines (wiki d-001 / d-002).
 */
function OpencodeExportSection() {
  const [host, setHost] = useState("127.0.0.1");
  const [exportData, setExportData] = useState<OpencodeExportResponse | null>(null);
  const [loading, setLoading] = useState(false);
  const [exportError, setExportError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  const generate = async (h: string) => {
    setLoading(true);
    setExportError(null);
    setCopied(false);
    try {
      const res = await fetchOpencodeExport(h || undefined);
      setExportData(res);
    } catch (err) {
      setExportData(null);
      setExportError(err instanceof Error ? err.message : String(err));
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    void generate(host);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const copy = async () => {
    if (!exportData?.text) return;
    try {
      await navigator.clipboard.writeText(exportData.text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Clipboard API unavailable (non-HTTPS context) — select the text instead.
      const el = document.getElementById("opencode-export-json") as HTMLTextAreaElement | null;
      el?.select();
      setExportError("Clipboard blocked — the JSON below is selected; press Ctrl+C to copy.");
    }
  };

  return (
    <div className="mb-3 rounded border border-border bg-surface-hover/30 px-3 py-3">
      <div className="mb-2 flex flex-wrap items-center gap-2">
        <span className="text-[10px] font-semibold uppercase tracking-wide text-muted">
          opencode.json provider block
        </span>
        <label className="ml-auto flex items-center gap-1.5 text-[10px] text-muted">
          CPA host
          <input
            type="text"
            value={host}
            onChange={(e) => setHost(e.target.value)}
            spellCheck={false}
            className="w-36 rounded border border-border bg-surface px-1.5 py-0.5 font-mono text-[11px] text-text-strong"
            title="CLIProxyAPI host the CLI reaches (port fixed at 8317). Default: 127.0.0.1 for same-host use."
          />
        </label>
        <button
          type="button"
          onClick={() => void generate(host)}
          disabled={loading}
          className="rounded border border-border px-2 py-0.5 text-[10px] font-semibold text-muted hover:bg-surface-hover hover:text-text-strong transition-colors disabled:opacity-50"
          title="Re-read config/model-registry.json and regenerate (no restart needed)"
        >
          {loading ? "generating…" : "regenerate"}
        </button>
        <button
          type="button"
          onClick={() => void copy()}
          disabled={!exportData}
          className="rounded border border-accent/50 bg-accent/10 px-2 py-0.5 text-[10px] font-semibold text-accent hover:bg-accent/20 transition-colors disabled:opacity-50"
        >
          {copied ? "copied ✓" : "copy"}
        </button>
      </div>

      {exportError && (
        <div className="mb-2 rounded border border-danger/30 bg-danger/10 px-2 py-1 text-[10px] text-danger">
          {exportError}
        </div>
      )}

      {exportData && exportData.warnings.length > 0 && (
        <div className="mb-2 flex flex-col gap-1">
          {exportData.warnings.map((w, i) => (
            <div key={i} className="rounded border border-warning/30 bg-warning/10 px-2 py-1 text-[10px] text-warning">
              {w}
            </div>
          ))}
        </div>
      )}

      {exportData ? (
        <>
          <textarea
            id="opencode-export-json"
            readOnly
            value={exportData.text}
            rows={Math.min(18, exportData.text.split("\n").length)}
            spellCheck={false}
            className="w-full resize-y rounded border border-border bg-surface px-2 py-2 font-mono text-[10px] leading-relaxed text-text-strong"
            onFocus={(e) => e.currentTarget.select()}
          />
          <div className="mt-1.5 text-[10px] text-muted">
            Paste into <span className="font-mono">opencode.json</span> (project root or{" "}
            <span className="font-mono">~/.config/opencode/opencode.json</span>). Models appear as{" "}
            <span className="font-mono">sparkdash/&lt;alias&gt;</span> in <span className="font-mono">/models</span>.
            Set <span className="font-mono">CPA_API_KEY</span> in your environment — the export carries no secrets.
          </div>
        </>
      ) : (
        !loading && <div className="py-2 text-center text-[11px] text-muted">Nothing to export yet.</div>
      )}
    </div>
  );
}

function ModelRow({ model, isLive }: { model: FleetModel; isLive: boolean }) {
  const [expanded, setExpanded] = useState(false);
  const u = model.usage;
  return (
    <div className="rounded border border-border bg-surface-hover/30">
      <button
        type="button"
        onClick={() => setExpanded((v) => !v)}
        className="flex w-full items-center gap-3 px-3 py-2 text-left hover:bg-surface-hover/50 transition-colors"
      >
        <span className={`ml-0.5 text-[10px] ${expanded ? "rotate-90" : ""} transition-transform text-muted`}>▶</span>
        <div className="min-w-0 flex-1">
          <div className="flex items-center gap-2">
            <span className="truncate font-mono text-xs font-semibold text-text-strong">{model.id}</span>
            {model.engine === "llama" ? <span className="rounded bg-surface-hover px-1.5 py-0.5 text-[9px] text-muted">llama.cpp</span>
              : <span className="rounded bg-surface-hover px-1.5 py-0.5 text-[9px] text-muted">vLLM</span>}
            {model.tensor_parallel > 1 && <span className="rounded bg-surface-hover px-1.5 py-0.5 text-[9px] text-muted">TP={model.tensor_parallel}</span>}
          </div>
          <div className="mt-0.5 flex items-center gap-2 text-[10px] text-muted">
            {(model.capability || []).slice(0, 3).map((c) => (
              <span key={c} className="rounded-full bg-accent/10 px-1.5 py-0.5 text-[9px] text-accent">{c}</span>
            ))}
            {model.hbm_gb > 0 && <span>{model.hbm_gb} GB HBM</span>}
            <span>{model.replicas.length} replica{model.replicas.length !== 1 ? "s" : ""}</span>
          </div>
        </div>
        <div className="flex shrink-0 items-center gap-3">
          <div className="hidden text-right sm:block">
            <div className="text-[10px] text-muted">lifetime in/out</div>
            <div className="font-tabular text-[11px] font-semibold text-text-strong">
              {fmtTokens(u?.promptTokens || 0)} / {fmtTokens(u?.completionTokens || 0)}
            </div>
          </div>
          <StatusBadge isLive={isLive} />
        </div>
      </button>

      {expanded && (
        <div className="border-t border-border px-3 py-3">
          <div className="mb-2 grid grid-cols-2 gap-3 text-[11px] sm:grid-cols-4">
            <Stat label="Requests" value={fmtCount(u?.requests || 0)} />
            <Stat label="Prompt tokens" value={fmtTokens(u?.promptTokens || 0)} />
            <Stat label="Generation tokens" value={fmtTokens(u?.completionTokens || 0)} />
            <Stat label="Last seen" value={u?.lastSeen ? new Date(u.lastSeen).toLocaleString() : "—"} />
          </div>

          {model.replicas.length > 0 && (
            <div className="mb-3">
              <div className="mb-1.5 text-[10px] font-semibold uppercase tracking-wide text-muted">Replicas</div>
              <div className="flex flex-col gap-1">
                {model.replicas.map((r) => (
                  <div key={`${r.node}:${r.port}`} className="flex items-center gap-2 rounded bg-surface-hover/40 px-2 py-1">
                    <span className={`h-1.5 w-1.5 rounded-full ${r.healthy === true ? "bg-success" : r.healthy === false ? "bg-danger" : "bg-muted/50"}`} />
                    <span className="font-mono text-[11px] text-text-strong">{r.node}:{r.port}</span>
                    <span className="text-[10px] text-muted">{r.host_port}</span>
                    <span className="ml-auto text-[10px] text-muted">{r.healthy === true ? "up" : r.healthy === false ? "down" : "unknown"}</span>
                  </div>
                ))}
              </div>
            </div>
          )}

          {u && u.users && u.users.length > 0 ? (
            <div>
              <div className="mb-1.5 text-[10px] font-semibold uppercase tracking-wide text-muted">All Users</div>
              <div className="flex flex-col gap-1">
                {u.users.map((usr) => (
                  <div key={usr.label || usr.clientIp} className="flex items-center gap-2 rounded bg-surface-hover/40 px-2 py-1 text-[11px]">
                    <span
                      className="min-w-0 flex-1 truncate font-mono text-text-strong"
                      title={usr.apiKeyPrefix ? `API key: ${usr.apiKeyPrefix}-***` : undefined}
                    >
                      {usr.apiKeyPrefix || usr.label}
                    </span>
                    <span className="text-muted">{fmtCount(usr.requests)} req</span>
                    <span className="font-tabular text-text-strong" title="Input tokens">{fmtTokens(usr.promptTokens)} in</span>
                    <span className="font-tabular text-accent" title="Output tokens">→ {fmtTokens(usr.completionTokens)} out</span>
                    {usr.lastSeen > 0 && (
                      <span className="hidden text-[9px] text-muted sm:inline">{fmtAgo(usr.lastSeen)}</span>
                    )}
                  </div>
                ))}
              </div>
            </div>
          ) : (
            <div className="text-[11px] text-muted">No per-user usage tracked for this model yet.</div>
          )}
        </div>
      )}
    </div>
  );
}

function Stat({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded bg-surface-hover/40 px-2 py-1.5">
      <div className="text-[9px] uppercase tracking-wide text-muted">{label}</div>
      <div className="font-tabular text-xs font-semibold text-text-strong">{value}</div>
    </div>
  );
}
