/**
 * ModelRegistry — loads the declarative fleet model registry generated by the
 * control plane (`fleet-sync.py` → config/model-registry.json) and exposes
 * per-model health/usage summary for the ModelFleet panel.
 *
 * This is the sparkDash side of the single-source-of-truth registry (DESIGN.md
 * §9). It does not edit the registry — it only reads the generated JSON and
 * merges *live* probe data (LLM health per node:port) so the dashboard reflects
 * the same reality routing uses.
 *
 * Key responsibilities:
 *   1. Load + validate config/model-registry.json (tolerates absence/poll).
 *   2. Coalesce aliases → canonical model id (alias_to_id from the generated
 *      file, so `claude-deepseek-v4-flash-0731` and the canonical id roll up
 *      into one row).
 *   3. Compute a per-model health level from per-node:port probes:
 *        green  = enough healthy replicas (>= min_healthy)
 *        yellow = some replicas down but min_healthy still met, or degraded
 *        red    = fewer healthy replicas than min_healthy (model effectively down)
 *   4. Attach live per-model usage (from PerUserModelUsageTracker) for the
 *      Model Usage History table.
 */
import fs from "fs";
import path from "path";
import { MODEL_REGISTRY_PATH, LLM_PROBE_TIMEOUT_MS } from "../config.js";
import { atomicWrite } from "../util/atomicWrite.js";

/** Healthy model-count status levels. */
export const HEALTH = { GREEN: "green", YELLOW: "yellow", RED: "red" };

/**
 * Coalesce a requested model id / alias to its canonical registry id.
 * Falls back to the input when the registry is absent or the id is unknown
 * (so the dashboard still shows live-served models not in the registry).
 * @param {string} id
 * @param {{alias_to_id?: Record<string,string>}|null} registry
 * @returns {string}
 */
export function coalesce(id, registry) {
  if (!id) return id;
  if (registry && registry.alias_to_id && registry.alias_to_id[id]) {
    return registry.alias_to_id[id];
  }
  return id;
}

/**
 * Evaluate per-model health given the registry + per node:port probe results.
 * @param {object} model  registry model entry (has min_healthy, node_ports)
 * @param {Array<{node:string,port:number,healthy:boolean}>} probes
 * @param {object} [opts]
 * @returns {{ level: string, healthy: number, required: number, total: number }}
 */
export function evaluateModelHealth(model, probes, opts = {}) {
  const required = Number(model?.min_healthy ?? opts.defaultMinHealthy ?? 1);
  const total = Number(model?.node_ports?.length ?? 0);
  const healthy = (probes || []).filter((p) => p && p.healthy).length;
  let level = HEALTH.RED;
  if (total === 0) {
    // No declared replicas — treat as unknown/not-run (red-ish, but distinct).
    level = HEALTH.RED;
  } else if (healthy >= required) {
    level = healthy < total ? HEALTH.YELLOW : HEALTH.GREEN;
  } else {
    level = HEALTH.RED;
  }
  return { level, healthy, required, total };
}

/**
 * Deep-merge small probe updates onto the persisted registry state so replica
 * health survives restart (mirrors SparkRegistry's persistence/event pattern).
 */
export function mergeState(prev, probeRow) {
  if (!probeRow || !probeRow.model_id) return prev;
  const next = {
    ...(prev || {}),
    probes: {
      ...((prev && prev.probes) || {}),
      [probeRow.model_id]: probeRow,
    },
  };
  return next;
}

/**
 * Live probe of every declared node:port for a registry (HTTP /health) via an
 * injected fetch so it is unit-testable without a network.
 * @param {object} registry
 * @param {Function} [healthFetch] async (url) => boolean — defaults to global fetch
 * @param {number} [timeoutMs]
 * @returns {Promise<Array<{model_id,node,port,host_port,healthy}>>}
 */
export async function probeRegistry(registry, healthFetch, timeoutMs = LLM_PROBE_TIMEOUT_MS) {
  if (!registry || !Array.isArray(registry.models)) return [];
  const doProbe =
    healthFetch ||
    (async (url) => {
      try {
        const ctl = new AbortController();
        const t = setTimeout(() => ctl.abort(), timeoutMs);
        try {
          const resp = await fetch(url, { signal: ctl.signal });
          return resp.ok;
        } finally {
          clearTimeout(t);
        }
      } catch {
        return false;
      }
    });

  const rows = [];
  for (const model of registry.models) {
    const nodePorts = Array.isArray(model.node_ports) ? model.node_ports : [];
    for (const np of nodePorts) {
      const url = `http://${np.host}:${np.port}/health`;
      let healthy = false;
      try {
        healthy = await doProbe(url);
      } catch {
        healthy = false;
      }
      rows.push({
        model_id: model.id,
        node: np.node,
        port: np.port,
        host_port: np.host_port || `${np.host}:${np.port}`,
        healthy,
      });
    }
  }
  return rows;
}

/**
 * Build the per-model fleet summary (health + placement) that the ModelFleet
 * panel renders. Pure — no I/O.
 * @param {object} registry  parsed model-registry.json
 * @param {Array}  probes    rows from probeRegistry()
 * @returns {Array<object>}
 */
export function buildModelFleet(registry, probes) {
  if (!registry || !Array.isArray(registry.models)) return [];
  const byModel = new Map();
  for (const p of probes || []) {
    if (!byModel.has(p.model_id)) byModel.set(p.model_id, []);
    byModel.get(p.model_id).push({ node: p.node, port: p.port, healthy: p.healthy });
  }
  return registry.models.map((model) => {
    const modelProbes = byModel.get(model.id) || [];
    const health = evaluateModelHealth(model, modelProbes);
    return {
      id: model.id,
      aliases: model.aliases || [],
      capability: model.capability || [],
      engine: model.engine || "",
      recipe: model.recipe || "",
      weights: model.weights || "",
      quantization: model.quantization || "",
      hbm_gb: model.hbm_gb || 0,
      tensor_parallel: model.tensor_parallel || 1,
      min_healthy: model.min_healthy || 1,
      health: {
        level: health.level,
        healthy: health.healthy,
        required: health.required,
        total: health.total,
      },
      replicas: (model.node_ports || []).map((np) => ({
        node: np.node,
        host: np.host,
        port: np.port,
        host_port: np.host_port || `${np.host}:${np.port}`,
        pin: np.pin || "",
        healthy: (modelProbes.find((p) => p.node === np.node && p.port === np.port) || {}).healthy ?? null,
      })),
    };
  });
}

export class ModelRegistry {
  constructor({ path: regPath = MODEL_REGISTRY_PATH } = {}) {
    this._path = regPath;
    this._registry = null;
    this._error = null;
    this._reload();
  }

  _reload() {
    try {
      if (fs.existsSync(this._path)) {
        const raw = fs.readFileSync(this._path, "utf8");
        this._registry = JSON.parse(raw);
        this._error = null;
      } else {
        this._registry = null;
      }
    } catch (err) {
      this._registry = null;
      this._error = err.message;
    }
  }

  get registry() {
    return this._registry;
  }

  get error() {
    return this._error;
  }

  /** Reload from disk (call after fleet-sync --apply runs). */
  reload() {
    this._reload();
  }

  /** Coalesce any id/alias to canonical. */
  coalesce(id) {
    return coalesce(id, this._registry);
  }

  /** True when registry is loaded. */
  get hasRegistry() {
    return Array.isArray(this._registry?.models) && this._registry.models.length > 0;
  }
}

// Re-export for convenience so callers can import either the class or helpers.
export default ModelRegistry;
